include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - example/**
  errors:
    # ปิดการแจ้งเตือนพวกนี้แบบถาวร
    unreachable_switch_default: ignore
    unused_import: ignore
    unused_local_variable: ignore
    deprecated_member_use: ignore

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    sort_child_properties_last: false